Desktop version
DiamondNath07/Portfolio pull request #5
Opened 2022-09-30 14:21 UTC by DiamondNath07

### This is the desktop version of my portfolio

It was built with the following;
- Index.html
- Styles.css
- linters.yml
 This version host a different background from the mobile version.

It is however responsive friendly.

2022-09-30 18:14 UTC, mckent05 requested changes
Hi @DiamondNath07, 

# STATUS: CHANGES REQUIRED ♻️ ♻️ 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![almost there](https://user-images.githubusercontent.com/73607512/193331787-242aa9cd-e6bd-4a8a-952a-7aec3657592d.gif)

## Highlights
- All linter checks are passing ✔️ ✔️ 
- Your project is gradually getting complete and it's looking quite nice 😄 😄 
- You have included a descriptive PR summary and PR title 👍 👍 

## Required Changes ♻️
## There are some issues I found with some parts of your mobile version, Please kindly fix the issue
- The texts in the about myself section in your portfolio are overlapping. Kindly fix this issue 😄 

Your project:
![current about me](https://user-images.githubusercontent.com/73607512/193330734-346087bc-b2ea-49a6-98d5-873868090ef2.PNG)

- The buttons in your project cards are not properly aligned, kindly please this issue for all your project cards 🙏 🙏 

Your project:
![figma 2 project card mobile](https://user-images.githubusercontent.com/73607512/193331286-04e4e495-c2c2-42e8-bd3a-0c283b138bce.PNG)


_Check the comments under the review._

## Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-30 18:14 UTC, mckent05 commented on index.html
> +    </div>
- There are few differences between your contact and the design in the Figma template. I'd kindly suggest you try to fix this 🙏 . Remember it is important that you try to replicate the Figma design as closely as possible to give confidence to recruiters in your ability to produce exact business requirements 🙏
Your design:
-- Please pay attention to the margin on the left side of the text, kindly fix this 👍 
-- Your contact form doesn't exactly match that of the design (there are two input fields for the name) 👍 
-- Your button is aligned as it is in the Figma template, kindly fix this 😄 😄 
![contact 5](https://user-images.githubusercontent.com/73607512/193329448-a1437ab4-c79c-489a-a35b-a4de00727ba1.PNG)

Figma design:
![contact figma2](https://user-images.githubusercontent.com/73607512/193329545-6d05ec60-b1d6-4727-a611-36243b8e0344.PNG)

- Also please fix your button alignment for the mobile version in your contact form 👍 
![current contact mobile](https://user-images.githubusercontent.com/73607512/193330352-6b165522-0087-4b48-970e-eadf44576c60.PNG)

2022-10-01 17:56 UTC, bobb-Rob requested changes
## STATUS: CHANGES REQUIRED ♻️

Hi @DiamondNath07 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![](https://camo.githubusercontent.com/34482800e1b92cb79ddca06edb4051edc407cb190f896e1e949e596aa9073851/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966)

 ## Highlights
✅ No Linter error
✅ Correct use of GitHub flow
✅ Very descriptive Pull Request(PR)
✅ Neat Commit messages


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-01 17:56 UTC, bobb-Rob commented on utils.html
> +          </div>
- [ ] [REQUIRED] The buttons are not showing on your desktop view on hover. Please note that the button should appear upon mouse hover. In other words, the projects cards before mouse hover have no button, but upon hover the button appears. Kindly implement that.

**Initial state** - When the project card is not hovered on with the mouse
![](https://user-images.githubusercontent.com/6615394/193140362-d2f81a7a-38e2-4c6b-a15d-b478e19911c6.png)

**On hover** - When the project is hovered on with the mouse
![](https://user-images.githubusercontent.com/6615394/193140366-4f4f21ea-9375-4dce-a6cb-c410a98eb080.png)


![image](https://user-images.githubusercontent.com/84156714/193421773-a1cc6de9-de85-4668-b199-d39c021bde44.png)

2022-10-01 20:07 UTC, awais-amjed requested changes
# STATUS: CHANGES REQUIRED ♻️

Hi @DiamondNath07 , 

Great work on making the changes requested by a previous reviewer 👏👏👏
You've done well implementing some of the requested changes, but there are still some which haven't been addressed yet.

## Highlights

- [x] Descriptive Pull Request ✔️
- [x] Nice Design ✔️
- [x] Good code organization ✔️ 

![gif](https://media.giphy.com/media/qLWdMYX1NYF2g/giphy-downsized-large.gif)

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-01 20:07 UTC, awais-amjed commented on index.html
> +          </div>
As mentioned by the previous reviewer, kindly make sure that the button should appear only upon mouse hover. I am attaching an image below explaining how it should work 🤗

![image](https://user-images.githubusercontent.com/73714615/193426503-6ef8d6be-d032-411d-a257-4aa9bb515c91.png)

2022-10-01 22:46 UTC, DiamondNath07 commented on index.html
> +          </div>
Please kindky understand that the hover effect required of me here is not possible with css as most of the prople who have done this project got a pass without this. I'm almost close to the deadline pls consider.

2022-10-01 23:25 UTC, mgmediaweb requested changes
Hi @DiamondNath07 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![almost2](https://user-images.githubusercontent.com/41912912/193431786-fb50e2fe-ed1c-454e-bd9a-2f9bd6083e33.gif)

 ## Highlights 💯 
- Good job following the advice of the previous reviewer ✔️ 
- I appreciate your effort, you can do it! ✔️ 

 ## Required Changes ♻️

![image](https://user-images.githubusercontent.com/41912912/193431772-f3055c02-9b0c-4cb9-9911-a52019525125.png)

_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-03 08:20 UTC, Lameck1 reviewed
Hello @DiamondNath07 👋,

_This is an additional review due to the second opinion request._

The code reviewer's only concern is that your app in its current state is unusable. Even if you do not use JavaScript for the hover effect, you still need to ensure that all the cards have the "See Project" button and are styled as in the provided design.

As the code reviewer has pointed out, one card's button is not visible and the other's button is not correctly styled. Please refactor the UI's design and ask for another code review.

Keep rocking 🚀!

2022-10-04 11:23 UTC, zieeco approved these changes
# status: APPROVED :green_circle: :100: 

Hi, @DiamondNath07, 


![68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f78543078657a514755357843444a754350652f67697068792e676966](https://user-images.githubusercontent.com/85113567/164945882-0a9554ea-956c-4fa0-a95c-379285283c1d.gif)


Good job so far on addressing the issue! 👍 Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


## Highlights ⚡ 

✅ Descriptive PR 👍 
✅ Nice design 🔥 
✅ Linters are passing 👏 


## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-04 12:11 UTC, merged